name: Build and Release App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # This is required for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/fermium'

          
      - name: Install dependencies
        run: npm install
        
      - name: Build app package
        run: npx @rocket.chat/apps-cli package
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 